In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/IRIS.csv')
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [4]:
from sklearn.preprocessing import LabelEncoder

species_encode = LabelEncoder()
df['species'] = species_encode.fit_transform(df['species'])
df.tail()

sepal_length  sepal_width  petal_length  petal_width  species
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

In [5]:
import numpy as np

df = np.array(df, dtype=np.float64)
X = df[:,:4]
y = df[:,4]
X[:5,:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [6]:
import math

def gaussian_function(data, mean, var):
    return (1.0/np.sqrt(2*math.pi*var)) * np.exp(-(data-mean)**2 / (2*var))

In [7]:
gaussian_function(X[:,0], X[:,0].mean(), X[:,0].var())

array([0.32221216, 0.25153438, 0.18516041, 0.15540296, 0.28678585,
       0.41844424, 0.15540296, 0.28678585, 0.10474977, 0.25153438,
       0.41844424, 0.21740064, 0.21740064, 0.08412707, 0.482724  ,
       0.47615441, 0.41844424, 0.32221216, 0.47615441, 0.32221216,
       0.41844424, 0.32221216, 0.15540296, 0.32221216, 0.21740064,
       0.28678585, 0.28678585, 0.3567385 , 0.3567385 , 0.18516041,
       0.21740064, 0.41844424, 0.3567385 , 0.44331983, 0.25153438,
       0.28678585, 0.44331983, 0.25153438, 0.10474977, 0.32221216,
       0.28678585, 0.12852697, 0.10474977, 0.28678585, 0.32221216,
       0.21740064, 0.32221216, 0.15540296, 0.3892081 , 0.28678585,
       0.18103867, 0.38504015, 0.21297773, 0.44331983, 0.35222808,
       0.47615441, 0.41477435, 0.25153438, 0.31751611, 0.3567385 ,
       0.28678585, 0.48225175, 0.47475831, 0.4605695 , 0.462829  ,
       0.28205344, 0.462829  , 0.482724  , 0.44029283, 0.462829  ,
       0.48225175, 0.4605695 , 0.41477435, 0.4605695 , 0.38504

In [8]:
def compute_base_probability(data):
  species = np.unique(y)
  species_prop = []
  for s in species:
    species_prop.append(len(np.where(data==s)[0]) / len(data))
  return species_prop
print(np.unique(y))
compute_base_probability(y)

[0. 1. 2.]


[0.3333333333333333, 0.3333333333333333, 0.3333333333333333]

In [17]:
def gaussian_bayes_classify(data, description=[5.2,4.6,3.7,2.8,1.3]):
  species = np.unique(y)
  species_prop = []
  for s in species:
    d = data[data[:,4] == s]
    prob = 1.0
    for i in range(len(description)):
      prob *= gaussian_function(description[i], d[:,i].mean(), d[:,i].var())
    species_prop.append(prob)
  max_prob = species_prop.index(max(species_prop))
  return species[max_prob]

gaussian_bayes_classify(df, description=[6.7,3,5.2,2.3])

2.0